### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by jkleinwaechter** [dtmilano/lex-bot-tester#6]
Excited to use the application! Unfortunately pip install lex-bot-tester fails. Looks like it fails when trying to uninstall the dateutil package. I've attached the log. Errors start in the bolded section.
Any ideas?
___

Collecting lex-bot-tester
  Using cached lex_bot_tester-1.0.4-py2.py3-none-any.whl
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from lex-bot-tester)
Requirement already satisfied: six in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from lex-bot-tester)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from lex-bot-tester)
Collecting boto3 (from lex-bot-tester)
  Using cached boto3-1.6.3-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests->lex-bot-tester)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests->lex-bot-tester)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests->lex-bot-tester)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests->lex-bot-tester)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /Library/Python/2.7/site-packages (from boto3->lex-bot-tester)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /Library/Python/2.7/site-packages (from boto3->lex-bot-tester)
Collecting botocore<1.10.0,>=1.9.3 (from boto3->lex-bot-tester)
  Using cached botocore-1.9.3-py2.py3-none-any.whl
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /Library/Python/2.7/site-packages (from s3transfer<0.2.0,>=0.1.10->boto3->lex-bot-tester)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.10.0,>=1.9.3->boto3->lex-bot-tester)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Requirement already satisfied: docutils>=0.10 in /Library/Python/2.7/site-packages (from botocore<1.10.0,>=1.9.3->boto3->lex-bot-tester)

**Installing collected packages: python-dateutil, botocore, boto3, lex-bot-tester
  Found existing installation: python-dateutil 1.5
    Uninstalling python-dateutil-1.5:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors**
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/easter.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/relativedelta.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/rrule.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tz.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/tzwin.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo/zoneinfo-2010g.tar.gz'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/zoneinfo'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil', '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil', "[Errno 1] Operation not permitted: '/var/folders/jy/xdv7r06s2hx87htlp70l3xt87vnqcz/T/pip-zdvoYu-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil'")]

**Comment by dtmilano** [comment]
There might be some incompatibilities with python 2.x.
Please try python 3.x.
The easiest way is perhaps to use a virtualenv (that's what I've used to test it).

**Comment by dtmilano** [comment]
You can create the virtualenv like this:

```shell
Diegos-Mac-mini:tmp diego$ virtualenv -p python3.6 myvenv-3.6
Running virtualenv with interpreter /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/diego/tmp/myvenv-3.6/bin/python3.6
Also creating executable in /Users/diego/tmp/myvenv-3.6/bin/python
Installing setuptools, pip, wheel...done.
Diegos-Mac-mini:tmp diego$ . myvenv-3.6/bin/activate
```

Install `lex-bot-tester`
```shell
(myvenv-3.6) Diegos-Mac-mini:tmp diego$ pip install lex-bot-tester
Collecting lex-bot-tester
  Downloading lex_bot_tester-1.0.4-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./myvenv-3.6/lib/python3.6/site-packages (from lex-bot-tester)
Collecting boto3 (from lex-bot-tester)
  Downloading boto3-1.6.3-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 2.5MB/s 
Collecting six (from lex-bot-tester)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting requests (from lex-bot-tester)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting botocore<1.10.0,>=1.9.3 (from boto3->lex-bot-tester)
  Downloading botocore-1.9.3-py2.py3-none-any.whl (4.1MB)
    100% |████████████████████████████████| 4.1MB 349kB/s 
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->lex-bot-tester)
  Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->lex-bot-tester)
  Using cached s3transfer-0.1.13-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->lex-bot-tester)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->lex-bot-tester)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->lex-bot-tester)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->lex-bot-tester)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.10.0,>=1.9.3->boto3->lex-bot-tester)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.10.0,>=1.9.3->boto3->lex-bot-tester)
  Using cached docutils-0.14-py3-none-any.whl
Installing collected packages: jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, chardet, idna, urllib3, certifi, requests, lex-bot-tester
Successfully installed boto3-1.6.3 botocore-1.9.3 certifi-2018.1.18 chardet-3.0.4 docutils-0.14 idna-2.6 jmespath-0.9.3 lex-bot-tester-1.0.4 python-dateutil-2.6.1 requests-2.18.4 s3transfer-0.1.13 six-1.11.0 urllib3-1.22
```

then run `urutu` or do whatever you want to do with it
```shell
(myvenv-3.6) Diegos-Mac-mini:tmp diego$ urutu --help
usage: urutu [--help | -H] {create-test [method-name [skill-name [intent-name]]]}
```
